set serveroutput on
set def off

prompt ORASVN.ORASVN.USER
@ORASVN.ORASVN.USER

prompt ORASVN.EXTPROCSHELL_LIB.LIBRARY
@ORASVN.EXTPROCSHELL_LIB.LIBRARY

prompt ORASVN.SOURCES.TABLE
@ORASVN.SOURCES.TABLE

prompt ORASVN.PROJECTS.TABLE
@ORASVN.PROJECTS.TABLE

prompt ORASVN.CSOURCE.TABLE
@ORASVN.CSOURCE.TABLE

prompt ORASVN.COMMANDS.TABLE
@ORASVN.COMMANDS.TABLE

prompt ORASVN.PROJECTS.TABLE_DATA
@ORASVN.PROJECTS.TABLE_DATA

prompt ORASVN.COMMANDS.TABLE_DATA
@ORASVN.COMMANDS.TABLE_DATA

prompt ORASVN.SOURCES.TABLE_DATA
@ORASVN.SOURCES.TABLE_DATA

prompt ORASVN.SVN.PACKAGE
@ORASVN.SVN.PACKAGE

prompt ORASVN.SVN_FILE.PACKAGE
@ORASVN.SVN_FILE.PACKAGE

prompt ORASVN.CMD.PACKAGE
@ORASVN.CMD.PACKAGE

prompt ORASVN.CLOB_CURSOR.PACKAGE
@ORASVN.CLOB_CURSOR.PACKAGE

prompt ORASVN.CC.PACKAGE
@ORASVN.CC.PACKAGE

prompt ORASVN.SVN_SOURCES_V.VIEW
@ORASVN.SVN_SOURCES_V.VIEW

prompt ORASVN.SRC_SEQ_V.VIEW
@ORASVN.SRC_SEQ_V.VIEW

prompt ORASVN.ALL_OBJECTS_V.VIEW
@ORASVN.ALL_OBJECTS_V.VIEW

prompt ORASVN.SYS_C004205.CONSTRAINT
@ORASVN.SYS_C004205.CONSTRAINT

prompt ORASVN.SYS_C004154.CONSTRAINT
@ORASVN.SYS_C004154.CONSTRAINT

prompt ORASVN.COMMANDS_UI.INDEX
@ORASVN.COMMANDS_UI.INDEX

prompt ORASVN.SOURCES_UI.INDEX
@ORASVN.SOURCES_UI.INDEX

prompt ORASVN.SYS_C004156.REF_CONSTRAINT
@ORASVN.SYS_C004156.REF_CONSTRAINT

prompt ORASVN.ISWIN.FUNCTION
@ORASVN.ISWIN.FUNCTION

prompt ORASVN.SHELL.FUNCTION
@ORASVN.SHELL.FUNCTION

prompt ORASVN.GETARGUMENTS.FUNCTION
@ORASVN.GETARGUMENTS.FUNCTION

prompt ORASVN.GETCOMMAND.FUNCTION
@ORASVN.GETCOMMAND.FUNCTION

prompt ORASVN.GETPATHSEPERATOR.FUNCTION
@ORASVN.GETPATHSEPERATOR.FUNCTION

prompt ORASVN.GETBITS.FUNCTION
@ORASVN.GETBITS.FUNCTION

prompt ORASVN.GETCDDL.FUNCTION
@ORASVN.GETCDDL.FUNCTION

prompt ORASVN.GETTABLEDATASQL.FUNCTION
@ORASVN.GETTABLEDATASQL.FUNCTION

prompt ORASVN.GETPATH.FUNCTION
@ORASVN.GETPATH.FUNCTION

prompt ORASVN.SVN_FILE.PACKAGE_BODY
@ORASVN.SVN_FILE.PACKAGE_BODY

prompt ORASVN.SVN.PACKAGE_BODY
@ORASVN.SVN.PACKAGE_BODY

prompt ORASVN.CMD.PACKAGE_BODY
@ORASVN.CMD.PACKAGE_BODY

prompt ORASVN.CLOB_CURSOR.PACKAGE_BODY
@ORASVN.CLOB_CURSOR.PACKAGE_BODY

prompt ORASVN.CC.PACKAGE_BODY
@ORASVN.CC.PACKAGE_BODY

prompt ORASVN.ORASVN.USER_GRANTS
@ORASVN.ORASVN.USER_GRANTS

prompt recomplie schema
exec sys.dbms_utility.compile_schema('ORASVN');
exec sys.dbms_utility.compile_schema('PUBLIC');

prompt ORASVN.extprocshell.C
@ORASVN.extprocshell.C

prompt PUBLIC.SVN_SOURCES_V.SYNONYM
@PUBLIC.SVN_SOURCES_V.SYNONYM

prompt PUBLIC.ALL_OBJECTS_V.SYNONYM
@PUBLIC.ALL_OBJECTS_V.SYNONYM

prompt PUBLIC.SVN.SYNONYM
@PUBLIC.SVN.SYNONYM

prompt recomplie schema
exec sys.dbms_utility.compile_schema('ORASVN');
exec sys.dbms_utility.compile_schema('PUBLIC');

exit;
