CREATE USER "ORASVN" IDENTIFIED BY VALUES '476BC503542F71B0'
      DEFAULT TABLESPACE "USERS"
      TEMPORARY TABLESPACE "TEMP";
 

  GRANT CREATE EXTERNAL JOB TO "ORASVN";
 
  GRANT CHANGE NOTIFICATION TO "ORASVN";
 
  GRANT EXEMPT IDENTITY POLICY TO "ORASVN";
 
  GRANT CREATE ANY SQL PROFILE TO "ORASVN";
 
  GRANT ADMINISTER ANY SQL TUNING SET TO "ORASVN";
 
  GRANT ADMINISTER SQL TUNING SET TO "ORASVN";
 
  GRANT ALTER ANY SQL PROFILE TO "ORASVN";
 
  GRANT DROP ANY SQL PROFILE TO "ORASVN";
 
  GRANT SELECT ANY TRANSACTION TO "ORASVN";
 
  GRANT MANAGE SCHEDULER TO "ORASVN";
 
  GRANT EXECUTE ANY CLASS TO "ORASVN";
 
  GRANT EXECUTE ANY PROGRAM TO "ORASVN";
 
  GRANT CREATE ANY JOB TO "ORASVN";
 
  GRANT CREATE JOB TO "ORASVN";
 
  GRANT ADVISOR TO "ORASVN";
 
  GRANT ANALYZE ANY DICTIONARY TO "ORASVN";
 
  GRANT IMPORT FULL DATABASE TO "ORASVN";
 
  GRANT EXPORT FULL DATABASE TO "ORASVN";
 
  GRANT GRANT ANY OBJECT PRIVILEGE TO "ORASVN";
 
  GRANT FLASHBACK ANY TABLE TO "ORASVN";
 
  GRANT DEBUG ANY PROCEDURE TO "ORASVN";
 
  GRANT DEBUG CONNECT SESSION TO "ORASVN";
 
  GRANT SELECT ANY DICTIONARY TO "ORASVN";
 
  GRANT RESUMABLE TO "ORASVN";
 
  GRANT EXEMPT ACCESS POLICY TO "ORASVN";
 
  GRANT ON COMMIT REFRESH TO "ORASVN";
 
  GRANT MERGE ANY VIEW TO "ORASVN";
 
  GRANT ADMINISTER DATABASE TRIGGER TO "ORASVN";
 
  GRANT DROP ANY OUTLINE TO "ORASVN";
 
  GRANT ALTER ANY OUTLINE TO "ORASVN";
 
  GRANT CREATE ANY OUTLINE TO "ORASVN";
 
  GRANT DROP ANY CONTEXT TO "ORASVN";
 
  GRANT CREATE ANY CONTEXT TO "ORASVN";
 
  GRANT DROP ANY DIMENSION TO "ORASVN";
 
  GRANT ALTER ANY DIMENSION TO "ORASVN";
 
  GRANT CREATE ANY DIMENSION TO "ORASVN";
 
  GRANT CREATE DIMENSION TO "ORASVN";
 
  GRANT UNDER ANY TABLE TO "ORASVN";
 
  GRANT EXECUTE ANY INDEXTYPE TO "ORASVN";
 
  GRANT GLOBAL QUERY REWRITE TO "ORASVN";
 
  GRANT QUERY REWRITE TO "ORASVN";
 
  GRANT UNDER ANY VIEW TO "ORASVN";
 
  GRANT DROP ANY INDEXTYPE TO "ORASVN";
 
  GRANT ALTER ANY INDEXTYPE TO "ORASVN";
 
  GRANT CREATE ANY INDEXTYPE TO "ORASVN";
 
  GRANT CREATE INDEXTYPE TO "ORASVN";
 
  GRANT EXECUTE ANY OPERATOR TO "ORASVN";
 
  GRANT DROP ANY OPERATOR TO "ORASVN";
 
  GRANT ALTER ANY OPERATOR TO "ORASVN";
 
  GRANT CREATE ANY OPERATOR TO "ORASVN";
 
  GRANT CREATE OPERATOR TO "ORASVN";
 
  GRANT EXECUTE ANY LIBRARY TO "ORASVN";
 
  GRANT DROP ANY LIBRARY TO "ORASVN";
 
  GRANT ALTER ANY LIBRARY TO "ORASVN";
 
  GRANT CREATE ANY LIBRARY TO "ORASVN";
 
  GRANT CREATE LIBRARY TO "ORASVN";
 
  GRANT UNDER ANY TYPE TO "ORASVN";
 
  GRANT EXECUTE ANY TYPE TO "ORASVN";
 
  GRANT DROP ANY TYPE TO "ORASVN";
 
  GRANT ALTER ANY TYPE TO "ORASVN";
 
  GRANT CREATE ANY TYPE TO "ORASVN";
 
  GRANT CREATE TYPE TO "ORASVN";
 
  GRANT DROP ANY DIRECTORY TO "ORASVN";
 
  GRANT CREATE ANY DIRECTORY TO "ORASVN";
 
  GRANT DROP ANY MATERIALIZED VIEW TO "ORASVN";
 
  GRANT ALTER ANY MATERIALIZED VIEW TO "ORASVN";
 
  GRANT CREATE ANY MATERIALIZED VIEW TO "ORASVN";
 
  GRANT CREATE MATERIALIZED VIEW TO "ORASVN";
 
  GRANT GRANT ANY PRIVILEGE TO "ORASVN";
 
  GRANT ANALYZE ANY TO "ORASVN";
 
  GRANT ALTER RESOURCE COST TO "ORASVN";
 
  GRANT DROP PROFILE TO "ORASVN";
 
  GRANT ALTER PROFILE TO "ORASVN";
 
  GRANT CREATE PROFILE TO "ORASVN";
 
  GRANT DROP ANY TRIGGER TO "ORASVN";
 
  GRANT ALTER ANY TRIGGER TO "ORASVN";
 
  GRANT CREATE ANY TRIGGER TO "ORASVN";
 
  GRANT CREATE TRIGGER TO "ORASVN";
 
  GRANT EXECUTE ANY PROCEDURE TO "ORASVN";
 
  GRANT DROP ANY PROCEDURE TO "ORASVN";
 
  GRANT ALTER ANY PROCEDURE TO "ORASVN";
 
  GRANT CREATE ANY PROCEDURE TO "ORASVN";
 
  GRANT CREATE PROCEDURE TO "ORASVN";
 
  GRANT FORCE ANY TRANSACTION TO "ORASVN";
 
  GRANT FORCE TRANSACTION TO "ORASVN";
 
  GRANT ALTER DATABASE TO "ORASVN";
 
  GRANT AUDIT ANY TO "ORASVN";
 
  GRANT ALTER ANY ROLE TO "ORASVN";
 
  GRANT GRANT ANY ROLE TO "ORASVN";
 
  GRANT DROP ANY ROLE TO "ORASVN";
 
  GRANT CREATE ROLE TO "ORASVN";
 
  GRANT DROP PUBLIC DATABASE LINK TO "ORASVN";
 
  GRANT CREATE PUBLIC DATABASE LINK TO "ORASVN";
 
  GRANT CREATE DATABASE LINK TO "ORASVN";
 
  GRANT SELECT ANY SEQUENCE TO "ORASVN";
 
  GRANT DROP ANY SEQUENCE TO "ORASVN";
 
  GRANT ALTER ANY SEQUENCE TO "ORASVN";
 
  GRANT CREATE ANY SEQUENCE TO "ORASVN";
 
  GRANT CREATE SEQUENCE TO "ORASVN";
 
  GRANT DROP ANY VIEW TO "ORASVN";
 
  GRANT CREATE ANY VIEW TO "ORASVN";
 
  GRANT CREATE VIEW TO "ORASVN";
 
  GRANT DROP PUBLIC SYNONYM TO "ORASVN";
 
  GRANT CREATE PUBLIC SYNONYM TO "ORASVN";
 
  GRANT DROP ANY SYNONYM TO "ORASVN";
 
  GRANT CREATE ANY SYNONYM TO "ORASVN";
 
  GRANT CREATE SYNONYM TO "ORASVN";
 
  GRANT DROP ANY INDEX TO "ORASVN";
 
  GRANT ALTER ANY INDEX TO "ORASVN";
 
  GRANT CREATE ANY INDEX TO "ORASVN";
 
  GRANT DROP ANY CLUSTER TO "ORASVN";
 
  GRANT ALTER ANY CLUSTER TO "ORASVN";
 
  GRANT CREATE ANY CLUSTER TO "ORASVN";
 
  GRANT CREATE CLUSTER TO "ORASVN";
 
  GRANT DELETE ANY TABLE TO "ORASVN";
 
  GRANT UPDATE ANY TABLE TO "ORASVN";
 
  GRANT INSERT ANY TABLE TO "ORASVN";
 
  GRANT SELECT ANY TABLE TO "ORASVN";
 
  GRANT COMMENT ANY TABLE TO "ORASVN";
 
  GRANT LOCK ANY TABLE TO "ORASVN";
 
  GRANT DROP ANY TABLE TO "ORASVN";
 
  GRANT BACKUP ANY TABLE TO "ORASVN";
 
  GRANT ALTER ANY TABLE TO "ORASVN";
 
  GRANT CREATE ANY TABLE TO "ORASVN";
 
  GRANT CREATE TABLE TO "ORASVN";
 
  GRANT DROP ROLLBACK SEGMENT TO "ORASVN";
 
  GRANT ALTER ROLLBACK SEGMENT TO "ORASVN";
 
  GRANT CREATE ROLLBACK SEGMENT TO "ORASVN";
 
  GRANT DROP USER TO "ORASVN";
 
  GRANT ALTER USER TO "ORASVN";
 
  GRANT BECOME USER TO "ORASVN";
 
  GRANT CREATE USER TO "ORASVN";
 
  GRANT UNLIMITED TABLESPACE TO "ORASVN";
 
  GRANT DROP TABLESPACE TO "ORASVN";
 
  GRANT MANAGE TABLESPACE TO "ORASVN";
 
  GRANT ALTER TABLESPACE TO "ORASVN";
 
  GRANT CREATE TABLESPACE TO "ORASVN";
 
  GRANT RESTRICTED SESSION TO "ORASVN";
 
  GRANT ALTER SESSION TO "ORASVN";
 
  GRANT CREATE SESSION TO "ORASVN";
 
  GRANT AUDIT SYSTEM TO "ORASVN";
 
  GRANT ALTER SYSTEM TO "ORASVN";
 
   GRANT "CONNECT" TO "ORASVN";
 
   GRANT "RESOURCE" TO "ORASVN";
 
   GRANT "DBA" TO "ORASVN";
 
   GRANT "SELECT_CATALOG_ROLE" TO "ORASVN";
 
   GRANT "EXECUTE_CATALOG_ROLE" TO "ORASVN";
 
   GRANT "DELETE_CATALOG_ROLE" TO "ORASVN";
 
   GRANT "EXP_FULL_DATABASE" TO "ORASVN";
 
   GRANT "IMP_FULL_DATABASE" TO "ORASVN";
 
   GRANT "RECOVERY_CATALOG_OWNER" TO "ORASVN";
 
   GRANT "GATHER_SYSTEM_STATISTICS" TO "ORASVN";
 
   GRANT "LOGSTDBY_ADMINISTRATOR" TO "ORASVN";
 
   GRANT "AQ_ADMINISTRATOR_ROLE" TO "ORASVN";
 
   GRANT "AQ_USER_ROLE" TO "ORASVN";
 
   GRANT "SCHEDULER_ADMIN" TO "ORASVN";
 
   GRANT "HS_ADMIN_ROLE" TO "ORASVN";
 
   GRANT "OEM_ADVISOR" TO "ORASVN";
 
   GRANT "OEM_MONITOR" TO "ORASVN";
 
   GRANT "PLUSTRACE" TO "ORASVN";
 
   GRANT "CTXAPP" TO "ORASVN";
 
   GRANT "XDBADMIN" TO "ORASVN";
 
   GRANT "AUTHENTICATEDUSER" TO "ORASVN";
 
   GRANT "XDBWEBSERVICES" TO "ORASVN";
 

