GRANT EXECUTE ON "SYS"."DBMS_SQLPLUS_SCRIPT" TO "ORASVN";
 
  GRANT DEBUG ON "SYS"."DBMS_SQLPLUS_SCRIPT" TO "ORASVN";
 
  GRANT READ ON DIRECTORY "SVN_SPOOL" TO "ORASVN" WITH GRANT OPTION;
 
  GRANT WRITE ON DIRECTORY "SVN_SPOOL" TO "ORASVN" WITH GRANT OPTION;
 
  GRANT READ ON DIRECTORY "ORACLE_LIB" TO "ORASVN" WITH GRANT OPTION;
 
  GRANT WRITE ON DIRECTORY "ORACLE_LIB" TO "ORASVN" WITH GRANT OPTION;
 
  GRANT READ ON DIRECTORY "SVN_PROJECTS" TO "ORASVN" WITH GRANT OPTION;
 
  GRANT WRITE ON DIRECTORY "SVN_PROJECTS" TO "ORASVN" WITH GRANT OPTION;
 
  GRANT READ ON DIRECTORY "ORASVN" TO "ORASVN" WITH GRANT OPTION;
 
  GRANT WRITE ON DIRECTORY "ORASVN" TO "ORASVN" WITH GRANT OPTION;
 
  GRANT READ ON DIRECTORY "OCI_H" TO "ORASVN" WITH GRANT OPTION;
 
  GRANT WRITE ON DIRECTORY "OCI_H" TO "ORASVN" WITH GRANT OPTION;
 
  GRANT READ ON DIRECTORY "ORASVN_SF" TO "ORASVN" WITH GRANT OPTION;
 
  GRANT WRITE ON DIRECTORY "ORASVN_SF" TO "ORASVN" WITH GRANT OPTION;
 
  GRANT READ ON DIRECTORY "L_ORANETTED" TO "ORASVN" WITH GRANT OPTION;
 
  GRANT WRITE ON DIRECTORY "L_ORANETTED" TO "ORASVN" WITH GRANT OPTION;
 
  GRANT READ ON DIRECTORY "ORANETTED_LOCAL" TO "ORASVN" WITH GRANT OPTION;
 
  GRANT WRITE ON DIRECTORY "ORANETTED_LOCAL" TO "ORASVN" WITH GRANT OPTION;
 
  GRANT READ ON DIRECTORY "ORANETTED_SF" TO "ORASVN" WITH GRANT OPTION;
 
  GRANT WRITE ON DIRECTORY "ORANETTED_SF" TO "ORASVN" WITH GRANT OPTION;
 
