CREATE OR REPLACE FORCE VIEW "ORASVN"."SVN_SOURCES_V" ("PROJECT_NAME", "OWNER", "TYPE", "NAME", "DATA_WHERE") AS 
  select "PROJECT_NAME","OWNER","TYPE","NAME","DATA_WHERE" from sources with read only;
 
